array< array< array<string> > > SPR_ANIM_TROO = {
	{
		{ "sprites/doom/imp/TROOA1_L3.spr", "sprites/doom/imp/TROOA2A8_L3.spr", "sprites/doom/imp/TROOA3A7_L3.spr", "sprites/doom/imp/TROOA4A6_L3.spr", "sprites/doom/imp/TROOA5_L3.spr", "sprites/doom/imp/TROOA6A4_L3.spr", "sprites/doom/imp/TROOA7A3_L3.spr", "sprites/doom/imp/TROOA8A2_L3.spr" },
		{ "sprites/doom/imp/TROOB1_L3.spr", "sprites/doom/imp/TROOB2B8_L3.spr", "sprites/doom/imp/TROOB3B7_L3.spr", "sprites/doom/imp/TROOB4B6_L3.spr", "sprites/doom/imp/TROOB5_L3.spr", "sprites/doom/imp/TROOB6B4_L3.spr", "sprites/doom/imp/TROOB7B3_L3.spr", "sprites/doom/imp/TROOB8B2_L3.spr" },
		{ "sprites/doom/imp/TROOC1_L3.spr", "sprites/doom/imp/TROOC2C8_L3.spr", "sprites/doom/imp/TROOC3C7_L3.spr", "sprites/doom/imp/TROOC4C6_L3.spr", "sprites/doom/imp/TROOC5_L3.spr", "sprites/doom/imp/TROOC6C4_L3.spr", "sprites/doom/imp/TROOC7C3_L3.spr", "sprites/doom/imp/TROOC8C2_L3.spr" },
		{ "sprites/doom/imp/TROOD1_L3.spr", "sprites/doom/imp/TROOD2D8_L3.spr", "sprites/doom/imp/TROOD3D7_L3.spr", "sprites/doom/imp/TROOD4D6_L3.spr", "sprites/doom/imp/TROOD5_L3.spr", "sprites/doom/imp/TROOD6D4_L3.spr", "sprites/doom/imp/TROOD7D3_L3.spr", "sprites/doom/imp/TROOD8D2_L3.spr" },
		{ "sprites/doom/imp/TROOE1_L3.spr", "sprites/doom/imp/TROOE2E8_L3.spr", "sprites/doom/imp/TROOE3E7_L3.spr", "sprites/doom/imp/TROOE4E6_L3.spr", "sprites/doom/imp/TROOE5_L3.spr", "sprites/doom/imp/TROOE6E4_L3.spr", "sprites/doom/imp/TROOE7E3_L3.spr", "sprites/doom/imp/TROOE8E2_L3.spr" },
		{ "sprites/doom/imp/TROOF1_L3.spr", "sprites/doom/imp/TROOF2F8_L3.spr", "sprites/doom/imp/TROOF3F7_L3.spr", "sprites/doom/imp/TROOF4F6_L3.spr", "sprites/doom/imp/TROOF5_L3.spr", "sprites/doom/imp/TROOF6F4_L3.spr", "sprites/doom/imp/TROOF7F3_L3.spr", "sprites/doom/imp/TROOF8F2_L3.spr" },
		{ "sprites/doom/imp/TROOG1_L3.spr", "sprites/doom/imp/TROOG2G8_L3.spr", "sprites/doom/imp/TROOG3G7_L3.spr", "sprites/doom/imp/TROOG4G6_L3.spr", "sprites/doom/imp/TROOG5_L3.spr", "sprites/doom/imp/TROOG6G4_L3.spr", "sprites/doom/imp/TROOG7G3_L3.spr", "sprites/doom/imp/TROOG8G2_L3.spr" },
		{ "sprites/doom/imp/TROOH1_L3.spr", "sprites/doom/imp/TROOH2H8_L3.spr", "sprites/doom/imp/TROOH3H7_L3.spr", "sprites/doom/imp/TROOH4H6_L3.spr", "sprites/doom/imp/TROOH5_L3.spr", "sprites/doom/imp/TROOH6H4_L3.spr", "sprites/doom/imp/TROOH7H3_L3.spr", "sprites/doom/imp/TROOH8H2_L3.spr" }
	},
	{
		{ "sprites/doom/imp/TROOA1_L2.spr", "sprites/doom/imp/TROOA2A8_L2.spr", "sprites/doom/imp/TROOA3A7_L2.spr", "sprites/doom/imp/TROOA4A6_L2.spr", "sprites/doom/imp/TROOA5_L2.spr", "sprites/doom/imp/TROOA6A4_L2.spr", "sprites/doom/imp/TROOA7A3_L2.spr", "sprites/doom/imp/TROOA8A2_L2.spr" },
		{ "sprites/doom/imp/TROOB1_L2.spr", "sprites/doom/imp/TROOB2B8_L2.spr", "sprites/doom/imp/TROOB3B7_L2.spr", "sprites/doom/imp/TROOB4B6_L2.spr", "sprites/doom/imp/TROOB5_L2.spr", "sprites/doom/imp/TROOB6B4_L2.spr", "sprites/doom/imp/TROOB7B3_L2.spr", "sprites/doom/imp/TROOB8B2_L2.spr" },
		{ "sprites/doom/imp/TROOC1_L2.spr", "sprites/doom/imp/TROOC2C8_L2.spr", "sprites/doom/imp/TROOC3C7_L2.spr", "sprites/doom/imp/TROOC4C6_L2.spr", "sprites/doom/imp/TROOC5_L2.spr", "sprites/doom/imp/TROOC6C4_L2.spr", "sprites/doom/imp/TROOC7C3_L2.spr", "sprites/doom/imp/TROOC8C2_L2.spr" },
		{ "sprites/doom/imp/TROOD1_L2.spr", "sprites/doom/imp/TROOD2D8_L2.spr", "sprites/doom/imp/TROOD3D7_L2.spr", "sprites/doom/imp/TROOD4D6_L2.spr", "sprites/doom/imp/TROOD5_L2.spr", "sprites/doom/imp/TROOD6D4_L2.spr", "sprites/doom/imp/TROOD7D3_L2.spr", "sprites/doom/imp/TROOD8D2_L2.spr" },
		{ "sprites/doom/imp/TROOE1_L2.spr", "sprites/doom/imp/TROOE2E8_L2.spr", "sprites/doom/imp/TROOE3E7_L2.spr", "sprites/doom/imp/TROOE4E6_L2.spr", "sprites/doom/imp/TROOE5_L2.spr", "sprites/doom/imp/TROOE6E4_L2.spr", "sprites/doom/imp/TROOE7E3_L2.spr", "sprites/doom/imp/TROOE8E2_L2.spr" },
		{ "sprites/doom/imp/TROOF1_L2.spr", "sprites/doom/imp/TROOF2F8_L2.spr", "sprites/doom/imp/TROOF3F7_L2.spr", "sprites/doom/imp/TROOF4F6_L2.spr", "sprites/doom/imp/TROOF5_L2.spr", "sprites/doom/imp/TROOF6F4_L2.spr", "sprites/doom/imp/TROOF7F3_L2.spr", "sprites/doom/imp/TROOF8F2_L2.spr" },
		{ "sprites/doom/imp/TROOG1_L2.spr", "sprites/doom/imp/TROOG2G8_L2.spr", "sprites/doom/imp/TROOG3G7_L2.spr", "sprites/doom/imp/TROOG4G6_L2.spr", "sprites/doom/imp/TROOG5_L2.spr", "sprites/doom/imp/TROOG6G4_L2.spr", "sprites/doom/imp/TROOG7G3_L2.spr", "sprites/doom/imp/TROOG8G2_L2.spr" },
		{ "sprites/doom/imp/TROOH1_L2.spr", "sprites/doom/imp/TROOH2H8_L2.spr", "sprites/doom/imp/TROOH3H7_L2.spr", "sprites/doom/imp/TROOH4H6_L2.spr", "sprites/doom/imp/TROOH5_L2.spr", "sprites/doom/imp/TROOH6H4_L2.spr", "sprites/doom/imp/TROOH7H3_L2.spr", "sprites/doom/imp/TROOH8H2_L2.spr" }
	},
	{
		{ "sprites/doom/imp/TROOA1_L1.spr", "sprites/doom/imp/TROOA2A8_L1.spr", "sprites/doom/imp/TROOA3A7_L1.spr", "sprites/doom/imp/TROOA4A6_L1.spr", "sprites/doom/imp/TROOA5_L1.spr", "sprites/doom/imp/TROOA6A4_L1.spr", "sprites/doom/imp/TROOA7A3_L1.spr", "sprites/doom/imp/TROOA8A2_L1.spr" },
		{ "sprites/doom/imp/TROOB1_L1.spr", "sprites/doom/imp/TROOB2B8_L1.spr", "sprites/doom/imp/TROOB3B7_L1.spr", "sprites/doom/imp/TROOB4B6_L1.spr", "sprites/doom/imp/TROOB5_L1.spr", "sprites/doom/imp/TROOB6B4_L1.spr", "sprites/doom/imp/TROOB7B3_L1.spr", "sprites/doom/imp/TROOB8B2_L1.spr" },
		{ "sprites/doom/imp/TROOC1_L1.spr", "sprites/doom/imp/TROOC2C8_L1.spr", "sprites/doom/imp/TROOC3C7_L1.spr", "sprites/doom/imp/TROOC4C6_L1.spr", "sprites/doom/imp/TROOC5_L1.spr", "sprites/doom/imp/TROOC6C4_L1.spr", "sprites/doom/imp/TROOC7C3_L1.spr", "sprites/doom/imp/TROOC8C2_L1.spr" },
		{ "sprites/doom/imp/TROOD1_L1.spr", "sprites/doom/imp/TROOD2D8_L1.spr", "sprites/doom/imp/TROOD3D7_L1.spr", "sprites/doom/imp/TROOD4D6_L1.spr", "sprites/doom/imp/TROOD5_L1.spr", "sprites/doom/imp/TROOD6D4_L1.spr", "sprites/doom/imp/TROOD7D3_L1.spr", "sprites/doom/imp/TROOD8D2_L1.spr" },
		{ "sprites/doom/imp/TROOE1_L1.spr", "sprites/doom/imp/TROOE2E8_L1.spr", "sprites/doom/imp/TROOE3E7_L1.spr", "sprites/doom/imp/TROOE4E6_L1.spr", "sprites/doom/imp/TROOE5_L1.spr", "sprites/doom/imp/TROOE6E4_L1.spr", "sprites/doom/imp/TROOE7E3_L1.spr", "sprites/doom/imp/TROOE8E2_L1.spr" },
		{ "sprites/doom/imp/TROOF1_L1.spr", "sprites/doom/imp/TROOF2F8_L1.spr", "sprites/doom/imp/TROOF3F7_L1.spr", "sprites/doom/imp/TROOF4F6_L1.spr", "sprites/doom/imp/TROOF5_L1.spr", "sprites/doom/imp/TROOF6F4_L1.spr", "sprites/doom/imp/TROOF7F3_L1.spr", "sprites/doom/imp/TROOF8F2_L1.spr" },
		{ "sprites/doom/imp/TROOG1_L1.spr", "sprites/doom/imp/TROOG2G8_L1.spr", "sprites/doom/imp/TROOG3G7_L1.spr", "sprites/doom/imp/TROOG4G6_L1.spr", "sprites/doom/imp/TROOG5_L1.spr", "sprites/doom/imp/TROOG6G4_L1.spr", "sprites/doom/imp/TROOG7G3_L1.spr", "sprites/doom/imp/TROOG8G2_L1.spr" },
		{ "sprites/doom/imp/TROOH1_L1.spr", "sprites/doom/imp/TROOH2H8_L1.spr", "sprites/doom/imp/TROOH3H7_L1.spr", "sprites/doom/imp/TROOH4H6_L1.spr", "sprites/doom/imp/TROOH5_L1.spr", "sprites/doom/imp/TROOH6H4_L1.spr", "sprites/doom/imp/TROOH7H3_L1.spr", "sprites/doom/imp/TROOH8H2_L1.spr" }
	},
	{
		{ "sprites/doom/imp/TROOA1_L0.spr", "sprites/doom/imp/TROOA2A8_L0.spr", "sprites/doom/imp/TROOA3A7_L0.spr", "sprites/doom/imp/TROOA4A6_L0.spr", "sprites/doom/imp/TROOA5_L0.spr", "sprites/doom/imp/TROOA6A4_L0.spr", "sprites/doom/imp/TROOA7A3_L0.spr", "sprites/doom/imp/TROOA8A2_L0.spr" },
		{ "sprites/doom/imp/TROOB1_L0.spr", "sprites/doom/imp/TROOB2B8_L0.spr", "sprites/doom/imp/TROOB3B7_L0.spr", "sprites/doom/imp/TROOB4B6_L0.spr", "sprites/doom/imp/TROOB5_L0.spr", "sprites/doom/imp/TROOB6B4_L0.spr", "sprites/doom/imp/TROOB7B3_L0.spr", "sprites/doom/imp/TROOB8B2_L0.spr" },
		{ "sprites/doom/imp/TROOC1_L0.spr", "sprites/doom/imp/TROOC2C8_L0.spr", "sprites/doom/imp/TROOC3C7_L0.spr", "sprites/doom/imp/TROOC4C6_L0.spr", "sprites/doom/imp/TROOC5_L0.spr", "sprites/doom/imp/TROOC6C4_L0.spr", "sprites/doom/imp/TROOC7C3_L0.spr", "sprites/doom/imp/TROOC8C2_L0.spr" },
		{ "sprites/doom/imp/TROOD1_L0.spr", "sprites/doom/imp/TROOD2D8_L0.spr", "sprites/doom/imp/TROOD3D7_L0.spr", "sprites/doom/imp/TROOD4D6_L0.spr", "sprites/doom/imp/TROOD5_L0.spr", "sprites/doom/imp/TROOD6D4_L0.spr", "sprites/doom/imp/TROOD7D3_L0.spr", "sprites/doom/imp/TROOD8D2_L0.spr" },
		{ "sprites/doom/imp/TROOE1_L0.spr", "sprites/doom/imp/TROOE2E8_L0.spr", "sprites/doom/imp/TROOE3E7_L0.spr", "sprites/doom/imp/TROOE4E6_L0.spr", "sprites/doom/imp/TROOE5_L0.spr", "sprites/doom/imp/TROOE6E4_L0.spr", "sprites/doom/imp/TROOE7E3_L0.spr", "sprites/doom/imp/TROOE8E2_L0.spr" },
		{ "sprites/doom/imp/TROOF1_L0.spr", "sprites/doom/imp/TROOF2F8_L0.spr", "sprites/doom/imp/TROOF3F7_L0.spr", "sprites/doom/imp/TROOF4F6_L0.spr", "sprites/doom/imp/TROOF5_L0.spr", "sprites/doom/imp/TROOF6F4_L0.spr", "sprites/doom/imp/TROOF7F3_L0.spr", "sprites/doom/imp/TROOF8F2_L0.spr" },
		{ "sprites/doom/imp/TROOG1_L0.spr", "sprites/doom/imp/TROOG2G8_L0.spr", "sprites/doom/imp/TROOG3G7_L0.spr", "sprites/doom/imp/TROOG4G6_L0.spr", "sprites/doom/imp/TROOG5_L0.spr", "sprites/doom/imp/TROOG6G4_L0.spr", "sprites/doom/imp/TROOG7G3_L0.spr", "sprites/doom/imp/TROOG8G2_L0.spr" },
		{ "sprites/doom/imp/TROOH1_L0.spr", "sprites/doom/imp/TROOH2H8_L0.spr", "sprites/doom/imp/TROOH3H7_L0.spr", "sprites/doom/imp/TROOH4H6_L0.spr", "sprites/doom/imp/TROOH5_L0.spr", "sprites/doom/imp/TROOH6H4_L0.spr", "sprites/doom/imp/TROOH7H3_L0.spr", "sprites/doom/imp/TROOH8H2_L0.spr" }
	}
};

array< array< array<string> > > SPR_ANIM_POSS = {
	{
		{ "sprites/doom/zombieman/POSSA1_L3.spr", "sprites/doom/zombieman/POSSA2A8_L3.spr", "sprites/doom/zombieman/POSSA3A7_L3.spr", "sprites/doom/zombieman/POSSA4A6_L3.spr", "sprites/doom/zombieman/POSSA5_L3.spr", "sprites/doom/zombieman/POSSA6A4_L3.spr", "sprites/doom/zombieman/POSSA7A3_L3.spr", "sprites/doom/zombieman/POSSA8A2_L3.spr" },
		{ "sprites/doom/zombieman/POSSB1_L3.spr", "sprites/doom/zombieman/POSSB2B8_L3.spr", "sprites/doom/zombieman/POSSB3B7_L3.spr", "sprites/doom/zombieman/POSSB4B6_L3.spr", "sprites/doom/zombieman/POSSB5_L3.spr", "sprites/doom/zombieman/POSSB6B4_L3.spr", "sprites/doom/zombieman/POSSB7B3_L3.spr", "sprites/doom/zombieman/POSSB8B2_L3.spr" },
		{ "sprites/doom/zombieman/POSSC1_L3.spr", "sprites/doom/zombieman/POSSC2C8_L3.spr", "sprites/doom/zombieman/POSSC3C7_L3.spr", "sprites/doom/zombieman/POSSC4C6_L3.spr", "sprites/doom/zombieman/POSSC5_L3.spr", "sprites/doom/zombieman/POSSC6C4_L3.spr", "sprites/doom/zombieman/POSSC7C3_L3.spr", "sprites/doom/zombieman/POSSC8C2_L3.spr" },
		{ "sprites/doom/zombieman/POSSD1_L3.spr", "sprites/doom/zombieman/POSSD2D8_L3.spr", "sprites/doom/zombieman/POSSD3D7_L3.spr", "sprites/doom/zombieman/POSSD4D6_L3.spr", "sprites/doom/zombieman/POSSD5_L3.spr", "sprites/doom/zombieman/POSSD6D4_L3.spr", "sprites/doom/zombieman/POSSD7D3_L3.spr", "sprites/doom/zombieman/POSSD8D2_L3.spr" },
		{ "sprites/doom/zombieman/POSSE1_L3.spr", "sprites/doom/zombieman/POSSE2E8_L3.spr", "sprites/doom/zombieman/POSSE3E7_L3.spr", "sprites/doom/zombieman/POSSE4E6_L3.spr", "sprites/doom/zombieman/POSSE5_L3.spr", "sprites/doom/zombieman/POSSE6E4_L3.spr", "sprites/doom/zombieman/POSSE7E3_L3.spr", "sprites/doom/zombieman/POSSE8E2_L3.spr" },
		{ "sprites/doom/zombieman/POSSF1_L3.spr", "sprites/doom/zombieman/POSSF2F8_L3.spr", "sprites/doom/zombieman/POSSF3F7_L3.spr", "sprites/doom/zombieman/POSSF4F6_L3.spr", "sprites/doom/zombieman/POSSF5_L3.spr", "sprites/doom/zombieman/POSSF6F4_L3.spr", "sprites/doom/zombieman/POSSF7F3_L3.spr", "sprites/doom/zombieman/POSSF8F2_L3.spr" },
		{ "sprites/doom/zombieman/POSSG1_L3.spr", "sprites/doom/zombieman/POSSG2G8_L3.spr", "sprites/doom/zombieman/POSSG3G7_L3.spr", "sprites/doom/zombieman/POSSG4G6_L3.spr", "sprites/doom/zombieman/POSSG5_L3.spr", "sprites/doom/zombieman/POSSG6G4_L3.spr", "sprites/doom/zombieman/POSSG7G3_L3.spr", "sprites/doom/zombieman/POSSG8G2_L3.spr" }
	},
	{
		{ "sprites/doom/zombieman/POSSA1_L2.spr", "sprites/doom/zombieman/POSSA2A8_L2.spr", "sprites/doom/zombieman/POSSA3A7_L2.spr", "sprites/doom/zombieman/POSSA4A6_L2.spr", "sprites/doom/zombieman/POSSA5_L2.spr", "sprites/doom/zombieman/POSSA6A4_L2.spr", "sprites/doom/zombieman/POSSA7A3_L2.spr", "sprites/doom/zombieman/POSSA8A2_L2.spr" },
		{ "sprites/doom/zombieman/POSSB1_L2.spr", "sprites/doom/zombieman/POSSB2B8_L2.spr", "sprites/doom/zombieman/POSSB3B7_L2.spr", "sprites/doom/zombieman/POSSB4B6_L2.spr", "sprites/doom/zombieman/POSSB5_L2.spr", "sprites/doom/zombieman/POSSB6B4_L2.spr", "sprites/doom/zombieman/POSSB7B3_L2.spr", "sprites/doom/zombieman/POSSB8B2_L2.spr" },
		{ "sprites/doom/zombieman/POSSC1_L2.spr", "sprites/doom/zombieman/POSSC2C8_L2.spr", "sprites/doom/zombieman/POSSC3C7_L2.spr", "sprites/doom/zombieman/POSSC4C6_L2.spr", "sprites/doom/zombieman/POSSC5_L2.spr", "sprites/doom/zombieman/POSSC6C4_L2.spr", "sprites/doom/zombieman/POSSC7C3_L2.spr", "sprites/doom/zombieman/POSSC8C2_L2.spr" },
		{ "sprites/doom/zombieman/POSSD1_L2.spr", "sprites/doom/zombieman/POSSD2D8_L2.spr", "sprites/doom/zombieman/POSSD3D7_L2.spr", "sprites/doom/zombieman/POSSD4D6_L2.spr", "sprites/doom/zombieman/POSSD5_L2.spr", "sprites/doom/zombieman/POSSD6D4_L2.spr", "sprites/doom/zombieman/POSSD7D3_L2.spr", "sprites/doom/zombieman/POSSD8D2_L2.spr" },
		{ "sprites/doom/zombieman/POSSE1_L2.spr", "sprites/doom/zombieman/POSSE2E8_L2.spr", "sprites/doom/zombieman/POSSE3E7_L2.spr", "sprites/doom/zombieman/POSSE4E6_L2.spr", "sprites/doom/zombieman/POSSE5_L2.spr", "sprites/doom/zombieman/POSSE6E4_L2.spr", "sprites/doom/zombieman/POSSE7E3_L2.spr", "sprites/doom/zombieman/POSSE8E2_L2.spr" },
		{ "sprites/doom/zombieman/POSSF1_L2.spr", "sprites/doom/zombieman/POSSF2F8_L2.spr", "sprites/doom/zombieman/POSSF3F7_L2.spr", "sprites/doom/zombieman/POSSF4F6_L2.spr", "sprites/doom/zombieman/POSSF5_L2.spr", "sprites/doom/zombieman/POSSF6F4_L2.spr", "sprites/doom/zombieman/POSSF7F3_L2.spr", "sprites/doom/zombieman/POSSF8F2_L2.spr" },
		{ "sprites/doom/zombieman/POSSG1_L2.spr", "sprites/doom/zombieman/POSSG2G8_L2.spr", "sprites/doom/zombieman/POSSG3G7_L2.spr", "sprites/doom/zombieman/POSSG4G6_L2.spr", "sprites/doom/zombieman/POSSG5_L2.spr", "sprites/doom/zombieman/POSSG6G4_L2.spr", "sprites/doom/zombieman/POSSG7G3_L2.spr", "sprites/doom/zombieman/POSSG8G2_L2.spr" }
	},
	{
		{ "sprites/doom/zombieman/POSSA1_L1.spr", "sprites/doom/zombieman/POSSA2A8_L1.spr", "sprites/doom/zombieman/POSSA3A7_L1.spr", "sprites/doom/zombieman/POSSA4A6_L1.spr", "sprites/doom/zombieman/POSSA5_L1.spr", "sprites/doom/zombieman/POSSA6A4_L1.spr", "sprites/doom/zombieman/POSSA7A3_L1.spr", "sprites/doom/zombieman/POSSA8A2_L1.spr" },
		{ "sprites/doom/zombieman/POSSB1_L1.spr", "sprites/doom/zombieman/POSSB2B8_L1.spr", "sprites/doom/zombieman/POSSB3B7_L1.spr", "sprites/doom/zombieman/POSSB4B6_L1.spr", "sprites/doom/zombieman/POSSB5_L1.spr", "sprites/doom/zombieman/POSSB6B4_L1.spr", "sprites/doom/zombieman/POSSB7B3_L1.spr", "sprites/doom/zombieman/POSSB8B2_L1.spr" },
		{ "sprites/doom/zombieman/POSSC1_L1.spr", "sprites/doom/zombieman/POSSC2C8_L1.spr", "sprites/doom/zombieman/POSSC3C7_L1.spr", "sprites/doom/zombieman/POSSC4C6_L1.spr", "sprites/doom/zombieman/POSSC5_L1.spr", "sprites/doom/zombieman/POSSC6C4_L1.spr", "sprites/doom/zombieman/POSSC7C3_L1.spr", "sprites/doom/zombieman/POSSC8C2_L1.spr" },
		{ "sprites/doom/zombieman/POSSD1_L1.spr", "sprites/doom/zombieman/POSSD2D8_L1.spr", "sprites/doom/zombieman/POSSD3D7_L1.spr", "sprites/doom/zombieman/POSSD4D6_L1.spr", "sprites/doom/zombieman/POSSD5_L1.spr", "sprites/doom/zombieman/POSSD6D4_L1.spr", "sprites/doom/zombieman/POSSD7D3_L1.spr", "sprites/doom/zombieman/POSSD8D2_L1.spr" },
		{ "sprites/doom/zombieman/POSSE1_L1.spr", "sprites/doom/zombieman/POSSE2E8_L1.spr", "sprites/doom/zombieman/POSSE3E7_L1.spr", "sprites/doom/zombieman/POSSE4E6_L1.spr", "sprites/doom/zombieman/POSSE5_L1.spr", "sprites/doom/zombieman/POSSE6E4_L1.spr", "sprites/doom/zombieman/POSSE7E3_L1.spr", "sprites/doom/zombieman/POSSE8E2_L1.spr" },
		{ "sprites/doom/zombieman/POSSF1_L1.spr", "sprites/doom/zombieman/POSSF2F8_L1.spr", "sprites/doom/zombieman/POSSF3F7_L1.spr", "sprites/doom/zombieman/POSSF4F6_L1.spr", "sprites/doom/zombieman/POSSF5_L1.spr", "sprites/doom/zombieman/POSSF6F4_L1.spr", "sprites/doom/zombieman/POSSF7F3_L1.spr", "sprites/doom/zombieman/POSSF8F2_L1.spr" },
		{ "sprites/doom/zombieman/POSSG1_L1.spr", "sprites/doom/zombieman/POSSG2G8_L1.spr", "sprites/doom/zombieman/POSSG3G7_L1.spr", "sprites/doom/zombieman/POSSG4G6_L1.spr", "sprites/doom/zombieman/POSSG5_L1.spr", "sprites/doom/zombieman/POSSG6G4_L1.spr", "sprites/doom/zombieman/POSSG7G3_L1.spr", "sprites/doom/zombieman/POSSG8G2_L1.spr" }
	},
	{
		{ "sprites/doom/zombieman/POSSA1_L0.spr", "sprites/doom/zombieman/POSSA2A8_L0.spr", "sprites/doom/zombieman/POSSA3A7_L0.spr", "sprites/doom/zombieman/POSSA4A6_L0.spr", "sprites/doom/zombieman/POSSA5_L0.spr", "sprites/doom/zombieman/POSSA6A4_L0.spr", "sprites/doom/zombieman/POSSA7A3_L0.spr", "sprites/doom/zombieman/POSSA8A2_L0.spr" },
		{ "sprites/doom/zombieman/POSSB1_L0.spr", "sprites/doom/zombieman/POSSB2B8_L0.spr", "sprites/doom/zombieman/POSSB3B7_L0.spr", "sprites/doom/zombieman/POSSB4B6_L0.spr", "sprites/doom/zombieman/POSSB5_L0.spr", "sprites/doom/zombieman/POSSB6B4_L0.spr", "sprites/doom/zombieman/POSSB7B3_L0.spr", "sprites/doom/zombieman/POSSB8B2_L0.spr" },
		{ "sprites/doom/zombieman/POSSC1_L0.spr", "sprites/doom/zombieman/POSSC2C8_L0.spr", "sprites/doom/zombieman/POSSC3C7_L0.spr", "sprites/doom/zombieman/POSSC4C6_L0.spr", "sprites/doom/zombieman/POSSC5_L0.spr", "sprites/doom/zombieman/POSSC6C4_L0.spr", "sprites/doom/zombieman/POSSC7C3_L0.spr", "sprites/doom/zombieman/POSSC8C2_L0.spr" },
		{ "sprites/doom/zombieman/POSSD1_L0.spr", "sprites/doom/zombieman/POSSD2D8_L0.spr", "sprites/doom/zombieman/POSSD3D7_L0.spr", "sprites/doom/zombieman/POSSD4D6_L0.spr", "sprites/doom/zombieman/POSSD5_L0.spr", "sprites/doom/zombieman/POSSD6D4_L0.spr", "sprites/doom/zombieman/POSSD7D3_L0.spr", "sprites/doom/zombieman/POSSD8D2_L0.spr" },
		{ "sprites/doom/zombieman/POSSE1_L0.spr", "sprites/doom/zombieman/POSSE2E8_L0.spr", "sprites/doom/zombieman/POSSE3E7_L0.spr", "sprites/doom/zombieman/POSSE4E6_L0.spr", "sprites/doom/zombieman/POSSE5_L0.spr", "sprites/doom/zombieman/POSSE6E4_L0.spr", "sprites/doom/zombieman/POSSE7E3_L0.spr", "sprites/doom/zombieman/POSSE8E2_L0.spr" },
		{ "sprites/doom/zombieman/POSSF1_L0.spr", "sprites/doom/zombieman/POSSF2F8_L0.spr", "sprites/doom/zombieman/POSSF3F7_L0.spr", "sprites/doom/zombieman/POSSF4F6_L0.spr", "sprites/doom/zombieman/POSSF5_L0.spr", "sprites/doom/zombieman/POSSF6F4_L0.spr", "sprites/doom/zombieman/POSSF7F3_L0.spr", "sprites/doom/zombieman/POSSF8F2_L0.spr" },
		{ "sprites/doom/zombieman/POSSG1_L0.spr", "sprites/doom/zombieman/POSSG2G8_L0.spr", "sprites/doom/zombieman/POSSG3G7_L0.spr", "sprites/doom/zombieman/POSSG4G6_L0.spr", "sprites/doom/zombieman/POSSG5_L0.spr", "sprites/doom/zombieman/POSSG6G4_L0.spr", "sprites/doom/zombieman/POSSG7G3_L0.spr", "sprites/doom/zombieman/POSSG8G2_L0.spr" }
	}
};

array< array< array<string> > > SPR_ANIM_SPOS = {
	{
		{ "sprites/doom/shotguy/SPOSA1_L3.spr", "sprites/doom/shotguy/SPOSA2A8_L3.spr", "sprites/doom/shotguy/SPOSA3A7_L3.spr", "sprites/doom/shotguy/SPOSA4A6_L3.spr", "sprites/doom/shotguy/SPOSA5_L3.spr", "sprites/doom/shotguy/SPOSA6A4_L3.spr", "sprites/doom/shotguy/SPOSA7A3_L3.spr", "sprites/doom/shotguy/SPOSA8A2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSB1_L3.spr", "sprites/doom/shotguy/SPOSB2B8_L3.spr", "sprites/doom/shotguy/SPOSB3B7_L3.spr", "sprites/doom/shotguy/SPOSB4B6_L3.spr", "sprites/doom/shotguy/SPOSB5_L3.spr", "sprites/doom/shotguy/SPOSB6B4_L3.spr", "sprites/doom/shotguy/SPOSB7B3_L3.spr", "sprites/doom/shotguy/SPOSB8B2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSC1_L3.spr", "sprites/doom/shotguy/SPOSC2C8_L3.spr", "sprites/doom/shotguy/SPOSC3C7_L3.spr", "sprites/doom/shotguy/SPOSC4C6_L3.spr", "sprites/doom/shotguy/SPOSC5_L3.spr", "sprites/doom/shotguy/SPOSC6C4_L3.spr", "sprites/doom/shotguy/SPOSC7C3_L3.spr", "sprites/doom/shotguy/SPOSC8C2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSD1_L3.spr", "sprites/doom/shotguy/SPOSD2D8_L3.spr", "sprites/doom/shotguy/SPOSD3D7_L3.spr", "sprites/doom/shotguy/SPOSD4D6_L3.spr", "sprites/doom/shotguy/SPOSD5_L3.spr", "sprites/doom/shotguy/SPOSD6D4_L3.spr", "sprites/doom/shotguy/SPOSD7D3_L3.spr", "sprites/doom/shotguy/SPOSD8D2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSE1_L3.spr", "sprites/doom/shotguy/SPOSE2E8_L3.spr", "sprites/doom/shotguy/SPOSE3E7_L3.spr", "sprites/doom/shotguy/SPOSE4E6_L3.spr", "sprites/doom/shotguy/SPOSE5_L3.spr", "sprites/doom/shotguy/SPOSE6E4_L3.spr", "sprites/doom/shotguy/SPOSE7E3_L3.spr", "sprites/doom/shotguy/SPOSE8E2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSF1_L3.spr", "sprites/doom/shotguy/SPOSF2F8_L3.spr", "sprites/doom/shotguy/SPOSF3F7_L3.spr", "sprites/doom/shotguy/SPOSF4F6_L3.spr", "sprites/doom/shotguy/SPOSF5_L3.spr", "sprites/doom/shotguy/SPOSF6F4_L3.spr", "sprites/doom/shotguy/SPOSF7F3_L3.spr", "sprites/doom/shotguy/SPOSF8F2_L3.spr" },
		{ "sprites/doom/shotguy/SPOSG1_L3.spr", "sprites/doom/shotguy/SPOSG2G8_L3.spr", "sprites/doom/shotguy/SPOSG3G7_L3.spr", "sprites/doom/shotguy/SPOSG4G6_L3.spr", "sprites/doom/shotguy/SPOSG5_L3.spr", "sprites/doom/shotguy/SPOSG6G4_L3.spr", "sprites/doom/shotguy/SPOSG7G3_L3.spr", "sprites/doom/shotguy/SPOSG8G2_L3.spr" }
	},
	{
		{ "sprites/doom/shotguy/SPOSA1_L2.spr", "sprites/doom/shotguy/SPOSA2A8_L2.spr", "sprites/doom/shotguy/SPOSA3A7_L2.spr", "sprites/doom/shotguy/SPOSA4A6_L2.spr", "sprites/doom/shotguy/SPOSA5_L2.spr", "sprites/doom/shotguy/SPOSA6A4_L2.spr", "sprites/doom/shotguy/SPOSA7A3_L2.spr", "sprites/doom/shotguy/SPOSA8A2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSB1_L2.spr", "sprites/doom/shotguy/SPOSB2B8_L2.spr", "sprites/doom/shotguy/SPOSB3B7_L2.spr", "sprites/doom/shotguy/SPOSB4B6_L2.spr", "sprites/doom/shotguy/SPOSB5_L2.spr", "sprites/doom/shotguy/SPOSB6B4_L2.spr", "sprites/doom/shotguy/SPOSB7B3_L2.spr", "sprites/doom/shotguy/SPOSB8B2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSC1_L2.spr", "sprites/doom/shotguy/SPOSC2C8_L2.spr", "sprites/doom/shotguy/SPOSC3C7_L2.spr", "sprites/doom/shotguy/SPOSC4C6_L2.spr", "sprites/doom/shotguy/SPOSC5_L2.spr", "sprites/doom/shotguy/SPOSC6C4_L2.spr", "sprites/doom/shotguy/SPOSC7C3_L2.spr", "sprites/doom/shotguy/SPOSC8C2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSD1_L2.spr", "sprites/doom/shotguy/SPOSD2D8_L2.spr", "sprites/doom/shotguy/SPOSD3D7_L2.spr", "sprites/doom/shotguy/SPOSD4D6_L2.spr", "sprites/doom/shotguy/SPOSD5_L2.spr", "sprites/doom/shotguy/SPOSD6D4_L2.spr", "sprites/doom/shotguy/SPOSD7D3_L2.spr", "sprites/doom/shotguy/SPOSD8D2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSE1_L2.spr", "sprites/doom/shotguy/SPOSE2E8_L2.spr", "sprites/doom/shotguy/SPOSE3E7_L2.spr", "sprites/doom/shotguy/SPOSE4E6_L2.spr", "sprites/doom/shotguy/SPOSE5_L2.spr", "sprites/doom/shotguy/SPOSE6E4_L2.spr", "sprites/doom/shotguy/SPOSE7E3_L2.spr", "sprites/doom/shotguy/SPOSE8E2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSF1_L2.spr", "sprites/doom/shotguy/SPOSF2F8_L2.spr", "sprites/doom/shotguy/SPOSF3F7_L2.spr", "sprites/doom/shotguy/SPOSF4F6_L2.spr", "sprites/doom/shotguy/SPOSF5_L2.spr", "sprites/doom/shotguy/SPOSF6F4_L2.spr", "sprites/doom/shotguy/SPOSF7F3_L2.spr", "sprites/doom/shotguy/SPOSF8F2_L2.spr" },
		{ "sprites/doom/shotguy/SPOSG1_L2.spr", "sprites/doom/shotguy/SPOSG2G8_L2.spr", "sprites/doom/shotguy/SPOSG3G7_L2.spr", "sprites/doom/shotguy/SPOSG4G6_L2.spr", "sprites/doom/shotguy/SPOSG5_L2.spr", "sprites/doom/shotguy/SPOSG6G4_L2.spr", "sprites/doom/shotguy/SPOSG7G3_L2.spr", "sprites/doom/shotguy/SPOSG8G2_L2.spr" }
	},
	{
		{ "sprites/doom/shotguy/SPOSA1_L1.spr", "sprites/doom/shotguy/SPOSA2A8_L1.spr", "sprites/doom/shotguy/SPOSA3A7_L1.spr", "sprites/doom/shotguy/SPOSA4A6_L1.spr", "sprites/doom/shotguy/SPOSA5_L1.spr", "sprites/doom/shotguy/SPOSA6A4_L1.spr", "sprites/doom/shotguy/SPOSA7A3_L1.spr", "sprites/doom/shotguy/SPOSA8A2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSB1_L1.spr", "sprites/doom/shotguy/SPOSB2B8_L1.spr", "sprites/doom/shotguy/SPOSB3B7_L1.spr", "sprites/doom/shotguy/SPOSB4B6_L1.spr", "sprites/doom/shotguy/SPOSB5_L1.spr", "sprites/doom/shotguy/SPOSB6B4_L1.spr", "sprites/doom/shotguy/SPOSB7B3_L1.spr", "sprites/doom/shotguy/SPOSB8B2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSC1_L1.spr", "sprites/doom/shotguy/SPOSC2C8_L1.spr", "sprites/doom/shotguy/SPOSC3C7_L1.spr", "sprites/doom/shotguy/SPOSC4C6_L1.spr", "sprites/doom/shotguy/SPOSC5_L1.spr", "sprites/doom/shotguy/SPOSC6C4_L1.spr", "sprites/doom/shotguy/SPOSC7C3_L1.spr", "sprites/doom/shotguy/SPOSC8C2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSD1_L1.spr", "sprites/doom/shotguy/SPOSD2D8_L1.spr", "sprites/doom/shotguy/SPOSD3D7_L1.spr", "sprites/doom/shotguy/SPOSD4D6_L1.spr", "sprites/doom/shotguy/SPOSD5_L1.spr", "sprites/doom/shotguy/SPOSD6D4_L1.spr", "sprites/doom/shotguy/SPOSD7D3_L1.spr", "sprites/doom/shotguy/SPOSD8D2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSE1_L1.spr", "sprites/doom/shotguy/SPOSE2E8_L1.spr", "sprites/doom/shotguy/SPOSE3E7_L1.spr", "sprites/doom/shotguy/SPOSE4E6_L1.spr", "sprites/doom/shotguy/SPOSE5_L1.spr", "sprites/doom/shotguy/SPOSE6E4_L1.spr", "sprites/doom/shotguy/SPOSE7E3_L1.spr", "sprites/doom/shotguy/SPOSE8E2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSF1_L1.spr", "sprites/doom/shotguy/SPOSF2F8_L1.spr", "sprites/doom/shotguy/SPOSF3F7_L1.spr", "sprites/doom/shotguy/SPOSF4F6_L1.spr", "sprites/doom/shotguy/SPOSF5_L1.spr", "sprites/doom/shotguy/SPOSF6F4_L1.spr", "sprites/doom/shotguy/SPOSF7F3_L1.spr", "sprites/doom/shotguy/SPOSF8F2_L1.spr" },
		{ "sprites/doom/shotguy/SPOSG1_L1.spr", "sprites/doom/shotguy/SPOSG2G8_L1.spr", "sprites/doom/shotguy/SPOSG3G7_L1.spr", "sprites/doom/shotguy/SPOSG4G6_L1.spr", "sprites/doom/shotguy/SPOSG5_L1.spr", "sprites/doom/shotguy/SPOSG6G4_L1.spr", "sprites/doom/shotguy/SPOSG7G3_L1.spr", "sprites/doom/shotguy/SPOSG8G2_L1.spr" }
	},
	{
		{ "sprites/doom/shotguy/SPOSA1_L0.spr", "sprites/doom/shotguy/SPOSA2A8_L0.spr", "sprites/doom/shotguy/SPOSA3A7_L0.spr", "sprites/doom/shotguy/SPOSA4A6_L0.spr", "sprites/doom/shotguy/SPOSA5_L0.spr", "sprites/doom/shotguy/SPOSA6A4_L0.spr", "sprites/doom/shotguy/SPOSA7A3_L0.spr", "sprites/doom/shotguy/SPOSA8A2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSB1_L0.spr", "sprites/doom/shotguy/SPOSB2B8_L0.spr", "sprites/doom/shotguy/SPOSB3B7_L0.spr", "sprites/doom/shotguy/SPOSB4B6_L0.spr", "sprites/doom/shotguy/SPOSB5_L0.spr", "sprites/doom/shotguy/SPOSB6B4_L0.spr", "sprites/doom/shotguy/SPOSB7B3_L0.spr", "sprites/doom/shotguy/SPOSB8B2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSC1_L0.spr", "sprites/doom/shotguy/SPOSC2C8_L0.spr", "sprites/doom/shotguy/SPOSC3C7_L0.spr", "sprites/doom/shotguy/SPOSC4C6_L0.spr", "sprites/doom/shotguy/SPOSC5_L0.spr", "sprites/doom/shotguy/SPOSC6C4_L0.spr", "sprites/doom/shotguy/SPOSC7C3_L0.spr", "sprites/doom/shotguy/SPOSC8C2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSD1_L0.spr", "sprites/doom/shotguy/SPOSD2D8_L0.spr", "sprites/doom/shotguy/SPOSD3D7_L0.spr", "sprites/doom/shotguy/SPOSD4D6_L0.spr", "sprites/doom/shotguy/SPOSD5_L0.spr", "sprites/doom/shotguy/SPOSD6D4_L0.spr", "sprites/doom/shotguy/SPOSD7D3_L0.spr", "sprites/doom/shotguy/SPOSD8D2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSE1_L0.spr", "sprites/doom/shotguy/SPOSE2E8_L0.spr", "sprites/doom/shotguy/SPOSE3E7_L0.spr", "sprites/doom/shotguy/SPOSE4E6_L0.spr", "sprites/doom/shotguy/SPOSE5_L0.spr", "sprites/doom/shotguy/SPOSE6E4_L0.spr", "sprites/doom/shotguy/SPOSE7E3_L0.spr", "sprites/doom/shotguy/SPOSE8E2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSF1_L0.spr", "sprites/doom/shotguy/SPOSF2F8_L0.spr", "sprites/doom/shotguy/SPOSF3F7_L0.spr", "sprites/doom/shotguy/SPOSF4F6_L0.spr", "sprites/doom/shotguy/SPOSF5_L0.spr", "sprites/doom/shotguy/SPOSF6F4_L0.spr", "sprites/doom/shotguy/SPOSF7F3_L0.spr", "sprites/doom/shotguy/SPOSF8F2_L0.spr" },
		{ "sprites/doom/shotguy/SPOSG1_L0.spr", "sprites/doom/shotguy/SPOSG2G8_L0.spr", "sprites/doom/shotguy/SPOSG3G7_L0.spr", "sprites/doom/shotguy/SPOSG4G6_L0.spr", "sprites/doom/shotguy/SPOSG5_L0.spr", "sprites/doom/shotguy/SPOSG6G4_L0.spr", "sprites/doom/shotguy/SPOSG7G3_L0.spr", "sprites/doom/shotguy/SPOSG8G2_L0.spr" }
	}
};

